### ISSUE TITLE
Multi state Widget

### ISSUE THREAD

**Issue by duczz** [iobroker-community-adapters/ioBroker.vis-material-advanced#14]
z.B. Licht (schalten) und Temperatur (Anzeige) in einem Widget.

**Comment by EdgarM73** [comment]
Hi duczz,

ich bin mir noch nicht sicher, ob das wirklich einen Mehrwert bringt. 

Ich könnte mir Maximal ein mixed widget aus Fenster/Tür Sensor und Temperatur/Luftfeuchte vorstellen.

Wenn du einen sauberen Usecase bringst, kann ich mich gerne daran setzen.

grüße
E

**Comment by duczz** [comment]
Hi Edgar, mich interessiert wenn ich auf meine VIS Übersicht schaue eben ob das Licht brennt oder wie warm es ist.
Ich kann aber auf einfach n anderes Widget über das Licht Widget legen, dann kannst den Issue schließen

**Comment by EdgarM73** [comment]
Hi @duczz ,

nein, mir ist bloss kein Usecase dazu eingefallen. Wenn du damit meinst, dass du eine bessere Übersicht haben willst könnte dir das hier vielleicht helfen:

Alle widgets sollen in Zukunft die Möglichkeit haben, das Icon und die Titel/subtitel ausblenden zu können.

Damit könntest du die widgets sehr klein machen und vielleicht genau das erreichen was du möchtest.

Ich könnte schon ein widget machen mit 2 DP, oder 3 oder 4 ;). Vielleicht schaff ich es auch ein widget mit einer konfigurierbaren Anzahl an DP zu erstellen.

nicht schliessen, vielleicht kommt noch jemand mit passenden Ideen :)

**Comment by EdgarM73** [comment]
Hi duczz,

im 0.6.1 ist ein widget dabei, das Temperaut und Luftfeuchtigkeit vereint.

Hast du sowas gemeint?

**Comment by duczz** [comment]
Ne, ich hätte eig. gerne Licht und Temperatur 🙈

**Comment by EdgarM73** [comment]
Vom Prinzip meinte ich. Nicht inhaltlich :)

**Comment by duczz** [comment]
Dann ja :)
