### ISSUE TITLE
ListLightDim - LightOnColor not working

### ISSUE THREAD

**Issue by akwak2015** [iobroker-community-adapters/ioBroker.vis-material-advanced#16]
**Describe the bug**  
The possibility to color the overlay of a widget with a color if the light is on has no effect on dimmer widget.

**To Reproduce**  
See Screenshot

**Expected behavior**  
Green Color on the widget as seen by the lightswitch

**Screenshots & Logfiles**  
![Material advanced](https://user-images.githubusercontent.com/15655548/95362648-ab96bd00-08ce-11eb-96ad-16c31915fb90.jpg)

**Versions:**  
 - Adapter version: 0.8.14
 - JS-Controller version: 3.1.6 
 - Node version: v12.18.4 
 - Operating system: ubuntu

**Additional context**  
N/A

**Comment by EdgarM73** [comment]
gefixt mit 0.9.1
