### ISSUE TITLE
ListThermostat mit Anzeige der Temperatur

### ISSUE THREAD

**Issue by mike-d-b** [iobroker-community-adapters/ioBroker.vis-material-advanced#21]
Ich würde mich über eine Anzeige der eingestellten bzw. einzustellenden Temperatur im ListThermostat Widget freuen. Damit ich beim Verwenden des Slides sehe welchen Wert ich gerade habe und einstellen möchte.
Entweder zusätzlich als neuen Wert oder wahlweise den Title oder Subtitle mit gewünschten Objekt IDs hinterlegen.

Aktuelle habe ich beim ListThermostat Widget einfach, das ListTemp Widget drüber gelegt.

![ListTempWidget](https://user-images.githubusercontent.com/76518883/102990756-383d3880-4518-11eb-97ce-4c044cbce307.PNG)

**Comment by EdgarM73** [comment]
Hi mike,

das ist jetzt schon möglich, einfach als Untertitel den Datenpunkt in geschweiften Klammern und ein °C dahinter

**Comment by mike-d-b** [comment]
Hi Edgar,
vielen Dank. Ja, funktioniert die Temperatur wird angezeigt.
Jetzt verhält sich der Slider leider nicht mehr, so wie von einem Slider erwartet. Ich kann ich nicht mehr sanft hin und her verschieben, sondern nur noch einmal anklicken. Beim Anklicken springt der Slider um ein px in die Höhe. Habe mal versucht das Widget größer zu machen, daran liegt das komische Verhalten nicht.
Das Verhalten tritt auch nur auf, wenn ich meine einzustellende Temperatur des Sliders mit dem Titel oder Untertitel anzeigen lasse, bei einem anderen Wert, welcher nicht mit dem Slider gekoppelt ist, tritt das Verhalten nicht auf.
Schade.

**Comment by EdgarM73** [comment]
Ich werde heute noch eine neue Version releasen, mit der man bei einigen Widgets den Untertitel automatisch mit dem Wert ersetzen kann.

Das Verhalten hatte ich heute auch mal kurz, ist aber wieder weg. bin selbst nicht ganz sicher warum.

grüße
E

**Comment by EdgarM73** [comment]
sollte mit der 1.3.1 jetzt gefixt sein.

entweder per Katze installieren oder morgen testen :)

**Comment by EdgarM73** [comment]
leider ist das Verhalten mit dem springendem slider auf meiner Prod Umgebung auch noch da :(
