### ISSUE TITLE
Incorrect alignment in ListText and ListNumber

### ISSUE THREAD

**Issue by alexandorrus** [iobroker-community-adapters/ioBroker.vis-material-advanced#22]
Before a reference to the source is made in the "Object ID" field, the center alignment is performed correctly as in other fully configured widgets. But as soon as I fill in this field, the padding-top style config disappears. Meanwhile, group_BoxStyle.value Vertical = Center

**To Reproduce**  

1.
![image](https://user-images.githubusercontent.com/40382630/111920147-7b1e9600-8a9e-11eb-89f9-fb15eac2935f.png)
![image](https://user-images.githubusercontent.com/40382630/111920106-4e6a7e80-8a9e-11eb-801a-5d8a1b5b24d2.png)

2. Set Object ID:
![image](https://user-images.githubusercontent.com/40382630/111920182-b15c1580-8a9e-11eb-94cf-6a7b6c0a5e3f.png)
![image](https://user-images.githubusercontent.com/40382630/111920172-a6a18080-8a9e-11eb-8ff9-9b7d9c006ca2.png)
![image](https://user-images.githubusercontent.com/40382630/111920223-de102d00-8a9e-11eb-83e8-c9874b837776.png)

I suggest the correct behavior is to stay centered like in other widgets

**Versions:**  
 - Adapter version: 1.3.0
 - JS-Controller version: 3.2.16
 - Node version: 14.6.0
 - Operating system: Raspbian GNU/Linux 10 (buster)

**Comment by EdgarM73** [comment]
added bugfix, thanks for the info
