### ISSUE TITLE
ListTemperatureHumid only shows temperature, not humidity

### ISSUE THREAD

**Issue by tron1911** [iobroker-community-adapters/ioBroker.vis-material-advanced#26]
**Describe the bug**  
The widget shows the temperature twice, no matter what the second DP (oid2) is set to, it shows the temperature (first DP) again followed by %...

**Versions:**  
 - Adapter version: 1.7
 - JS-Controller version: <js-controller-version>  3.2.16
 - Node version: <node-version>  12.22
 - Operating system: Ubuntu 20.04

**Additional context**  
All other widgets work fine, thanks for this very nice adapter :)

![image](https://user-images.githubusercontent.com/86683927/123851048-0e2b5f80-d91b-11eb-84a4-7fa678af995e.png)
![image](https://user-images.githubusercontent.com/86683927/123851104-1d121200-d91b-11eb-9151-9fb3cde5b0bb.png)
![image](https://user-images.githubusercontent.com/86683927/123851174-2f8c4b80-d91b-11eb-96a1-60eca747e5d1.png)

**Comment by EdgarM73** [comment]
hi @tron1911 ,

danke für den Hinweis, ist sehr seltsam, weil ich da schon lange nichts geändert habe ( absichtlich :) ).

ist mit 1.7.2 gefixt.

grüße
E
